export const LOGIN_ROUTE = 'login'
export const LABORATORY_ROUTE = 'Laboratory'
export const STUDLABORATORY_ROUTE = 'StudLaboratory'
export const MAIN_ROUTE = '/'
export const EDITINGLABOTATORYPREP_ROUTE = 'editingLaboratoryPrep'
export const REGISTRATION_ROUTE = 'Registration'
export const PROFILE_ROUTE = 'profile'
export const LABORATORYADD_ROUTE = 'LaboratoryAdd'